'use strict';var type='';var imgRender='';function randomString(length=10){var out="";var pool="ABCDEFGHJKLMNOPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz0123456789?/:@-._~!$&'()*+,;=";var random=undefined;for(var i=0;i<length;i++){try{random=(window.crypto.getRandomValues(new Uint8Array(1))[0]/255)}catch(err){random=undefined}
if(random===null||random===undefined||isNaN(random)||random>1||random<0){random=Math.random()}
out+=pool.charAt(Math.floor(random*pool.length));random=undefined}
return out}
function resizeImg(source){$$('form').addClass('h');msg('Tuning the image, please wait...');var img=new Image();var resize=0;var size=0;var minQuality=0.3;var quality=minQuality;var previous='';var current='';img.onload=function(){var canvas=document.createElement('canvas');var ctx=canvas.getContext('2d');var width=img.width;var height=img.height;var original=height*width;canvas.width=width;canvas.height=height;while(size<=30700&&quality<=1){previous=current;ctx.clearRect(0,0,width,height);ctx.drawImage(img,0,0,width,height);current=canvas.toDataURL('image/jpeg',quality);size=current.length;if(quality==minQuality&&size>30700){resize+=1;width*=0.8;height*=0.8;canvas.width=width;canvas.height=height;size=0}else{quality+=0.01}}
msg('Image tuned: quality at '+Math.round(quality*100)+'%, and resized to '+Math.round(100*(width*height)/original)+'% the original size');$$('form').removeClass('h');imgRender=previous;$$('#preview').prop('src',previous)}
img.src=source}
function setInput(active){$$('#url,#text,#img').each(function(x){x.disabled=!0});$$('#'+active).first().disabled=!1;type=active}
$$().ready(function(){$$('#alert').onClick(function(){closeAlert()});$$('.tabf').onClick(function(e){e.preventDefault();var target=this.getAttribute('for');var allButtons=$$('.tabf');if(target=='img'){$$('.noImage').addClass('h')}else{$$('.noImage').removeClass('h')}
allButtons.addClass('btn--gray');allButtons.removeClass('btn--blue');this.classList.remove('btn--gray');this.classList.add('btn--blue');$$('.tabt > div').addClass('h');$$('#'+target+'-tab').removeClass('h');setInput(target)});$$('#showopt').onClick(function(e){e.preventDefault();$$('#extras').toggleClass('h')});$$('.change').onClick(function(e){e.preventDefault();var target=$$('#'+this.getAttribute('data-target'));var change=parseInt(this.getAttribute('data-delta'))+parseInt(target.val());if(change>target.prop('max')){target.val(target.prop('max'))}else if(change<target.prop('min')){target.val(target.prop('min'))}else{target.val(change)}});$$('input[type="checkbox"]').event('change',function(){var target=this.getAttribute('for');if(target!==null)$$('#'+target).first().disabled=!this.checked;if(target==='edit'&&$$('#optStats').first().checked)$$('#optStats').select();if(target==='stats'){if(this.checked){$$('#clicks').first().min=10}else{$$('#clicks').first().min=1}
if($$('#optEdit').first().checked)$$('#optEdit').select()}});$$('#img').event('change',function(){if($$('#img').val().length<3){$$('#preview').prop('src','');return}
var imgFile=$$('#img').first().files[0];try{var reader=new FileReader();reader.onloadend=function(){if(reader.result.length>30700){resizeImg(reader.result)}else{imgRender=reader.result;$$('#preview').prop('src',reader.result)}}
reader.readAsDataURL(imgFile)}catch(err){console.log(err);msg('Your browser doesn\'t support this feature')}});$$('form').event('submit',function(e){e.preventDefault();$$('form').addClass('h');closeAlert();var clicks=parseInt($$('#clicks').val())
var hours=parseInt($$('#hours').val())
var data=$$('#url').val();if(type=='text')data=$$('#text').val();if(type=='img'){data=imgRender;clicks=1;hours=1}
apiSet(function(status){if(status){$$('#final').val(baseUrl+($$('#stats').first().checked?'track/':'')+$$('#link').val());var remember='';if($$('#optPassword').first().checked)remember+='Your link password is <code>'+$$('#password').val()+'</code><br>';if($$('#optDel').first().checked&&$$('#del').val()!=='')remember+='Your delete password is <code>'+$$('#del').val()+'</code><br>';if($$('#optDel').first().checked&&$$('#del').val()==='')remember+='You have enabled public deletion<br>';if($$('#optEdit').first().checked)remember+='Your edit password is <code>'+$$('#edit').val()+'</code><br>';if($$('#optStats').first().checked&&$$('#stats').val()!=='')remember+='Your stats password is <code>'+$$('#stats').val()+'</code><br>';if($$('#optStats').first().checked&&$$('#stats').val()==='')remember+='You have enabled public stats<br>';$$('#remember').html(remember);$$('.ready').removeClass('h')}else{msg('Link taken, try another link',!1);$$('form').removeClass('h')}},data,$$('#link').val(),type,clicks,hours,($$('#optPassword').first().checked?$$('#password').val():!1),($$('#optDel').first().checked?$$('#del').val():!1),($$('#optEdit').first().checked?$$('#edit').val():!1),($$('#optStats').first().checked?$$('#stats').val():!1),(type=='img'))});$$('#copy').onClick(function(e){e.preventDefault();var toSelect=$$('#final').first();toSelect.setSelectionRange(0,toSelect.value.length);toSelect.select();document.execCommand("copy")});$$('#close').onClick(function(e){e.preventDefault();$$('#link').val(randomString());$$('form').removeClass('h');$$('.ready').addClass('h')});$$('.random').onClick(function(e){e.preventDefault();$$('#'+this.getAttribute('for')).val(randomString(30))})
$$('#link').val(randomString());setInput('url');$$('.disOnStart').each(function(toDisable){toDisable.disabled=!0})})